server:
  port: 8080
spring:
  #  加载数据源
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
  #   配置jpa
  jpa:
    database: MySQL
    #    hibernate方言
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      #      指定ddl语句的形式，自动根据实体创建表。有四个属性可配置
      #      create—-每次运行该程序，没有表格会新建表格，表内有数据会清空
      #      create-drop—-每次程序结束的时候会清空表
      #      update—-每次运行程序，没有表格会新建表格，表内有数据不会清空，只会更新
      #      validate—-运行程序会校验数据与数据库的字段类型是否相同，不同会报错
      ddl-auto: update
      naming:
        #        是否在日志里打印出sql语句，默认为false
        show-sql: true
        properties:
          #          是否格式化生成的sql语句，默认为false。
          hibernate.format_sql: true
        #          建表的命名规则,生成的数据库字段名带有下划线分隔
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    # 配置初始化大小、最小、最大
    maxActive: 20
    initialSize: 5
    minIdle: 5
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
  #    时间转换
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8